# Generated by Django 4.1.7 on 2023-10-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaning',
            old_name='cleaning_id',
            new_name='task_id',
        ),
    ]
