# Generated by Django 4.1.7 on 2023-10-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0002_rename_cleaning_id_cleaning_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
